package vn.unlimit.vpngate.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette (mirrors res/values/colors.xml)
val PrimaryLight = Color(0xFF4F46E5)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFE0E7FF)
val OnPrimaryContainerLight = Color(0xFF1E1B4B)
val PrimaryDarkLight = Color(0xFF3730A3)
val SecondaryLight = Color(0xFF0D9488)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCFBF1)
val OnSecondaryContainerLight = Color(0xFF134E4A)
val TertiaryLight = Color(0xFF14B8A6)
val BackgroundLight = Color(0xFFF8FAFC)
val OnBackgroundLight = Color(0xFF0F172A)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF0F172A)
val SurfaceVariantLight = Color(0xFFEEF2FF)
val OnSurfaceVariantLight = Color(0xFF334155)
val SurfaceElevatedLight = Color(0xFFFFFFFF)
val ErrorLight = Color(0xFFDC2626)
val ErrorContainerLight = Color(0xFFFEE2E2)
val OnErrorContainerLight = Color(0xFF7F1D1D)
val OutlineLight = Color(0xFFCBD5E1)

// Dark palette (mirrors res/values-night/colors.xml)
val PrimaryDark = Color(0xFF818CF8)
val OnPrimaryDark = Color(0xFF0F172A)
val PrimaryContainerDark = Color(0xFF312E81)
val OnPrimaryContainerDark = Color(0xFFE0E7FF)
val PrimaryDarkDark = Color(0xFF1E1B4B)
val SecondaryDark = Color(0xFF2DD4BF)
val OnSecondaryDark = Color(0xFF042F2E)
val SecondaryContainerDark = Color(0xFF134E4A)
val OnSecondaryContainerDark = Color(0xFFCCFBF1)
val TertiaryDark = Color(0xFF2DD4BF)
val BackgroundDark = Color(0xFF0F172A)
val OnBackgroundDark = Color(0xFFF1F5F9)
val SurfaceDark = Color(0xFF1E293B)
val OnSurfaceDark = Color(0xFFF1F5F9)
val SurfaceVariantDark = Color(0xFF312E81)
val OnSurfaceVariantDark = Color(0xFFE2E8F0)
val SurfaceElevatedDark = Color(0xFF253044)
val ErrorDark = Color(0xFFF87171)
val ErrorContainerDark = Color(0xFF7F1D1D)
val OnErrorContainerDark = Color(0xFFFECACA)
val OutlineDark = Color(0xFF475569)

// Status / semantic tokens (same in both modes, tuned per mode)
val AutoDisconnectedLight = Color(0xFFEF4444)
val AutoDisconnectedDark = Color(0xFFF87171)
val AutoConnectingLight = Color(0xFFF59E0B)
val AutoConnectingDark = Color(0xFFFBBF24)
val AutoConnectedLight = Color(0xFF10B981)
val AutoConnectedDark = Color(0xFF34D399)

val LinkLight = Color(0xFF2563EB)
val LinkDark = Color(0xFF60A5FA)
val GoodStatusLight = Color(0xFF059669)
val GoodStatusDark = Color(0xFF34D399)
