"""
Mission §31 Tests 1/5/6/7 — DOM-based HTML parsing against a REAL
VPN Gate snapshot (tests/fixtures/vpngate_table_sample.html,
generated by tests/make_fixture.py).
"""
import re

import pytest
from bs4 import BeautifulSoup

import vpngate_collector as vg


@pytest.fixture(scope="module")
def fixture_html() -> str:
    with open(
        "tests/fixtures/vpngate_table_sample.html",
        encoding="utf-8",
    ) as f:
        return f.read()


@pytest.fixture(scope="module")
def servers(fixture_html):
    return {
        s["identity"]["hostname"]: s
        for s in vg.parse_html(fixture_html, "html")
    }


def _row_cells(tr):
    return [c.get_text(" ", strip=True) for c in tr.find_all("td")]


def _row_for_host(fixture_html: str, needle: str):
    """Independent mini-extractor used ONLY by tests as ground truth
    (different code path from the collector's own logic)."""
    soup = BeautifulSoup(fixture_html, "html.parser")

    for table in soup.find_all("table", id="vg_hosts_table_id"):
        for tr in table.find_all("tr"):
            text = tr.get_text(" ", strip=True)

            if needle in text:
                return tr

    return None


def test_fixture_is_real_vpngate_dom(fixture_html):
    assert "vg_hosts_table_id" in fixture_html
    assert "opengw.net" in fixture_html


def test_1_full_record_public_vpn_206(servers, fixture_html):
    """§31 Test 1: one REAL record; protocol fields verified against
    that very row's raw cells (no guessing anywhere)."""
    server = servers.get("public-vpn-206.opengw.net")

    assert server is not None, "public-vpn-206 missing from snapshot"

    identity = server["identity"]
    assert identity["hostname"] == "public-vpn-206.opengw.net"
    assert identity["ip"] == "219.100.37.165"
    assert identity["country"] == "JP"          # ISO from flag image
    assert identity["countryLong"] == "Japan"

    tr = _row_for_host(fixture_html, "219.100.37.165")
    assert tr is not None

    cells = _row_cells(tr)

    def find_cell(snippet: str) -> str:
        return next((c for c in cells if snippet in c), "")

    p = server["protocols"]

    # --- SoftEther: STRICTLY from the SSL-VPN cell ---
    se_cell = find_cell("SSL-VPN")
    assert se_cell, "SSL-VPN cell absent"

    se_tcp_m = re.search(r"TCP\s*:\s*(\d+)", se_cell)

    if se_tcp_m:
        assert p["softether"]["tcp"]["supported"] is True
        assert p["softether"]["tcp"]["port"] == int(se_tcp_m.group(1))
    else:
        assert p["softether"]["tcp"]["supported"] is False
        assert p["softether"]["tcp"]["port"] is None

    if re.search(r"UDP\s*:\s*Supported", se_cell):
        assert p["softether"]["udp"]["supported"] is True
        assert p["softether"]["udp"]["port"] is None   # §6

    # --- OpenVPN: URL params are authoritative ---
    a = tr.find("a", href=lambda h: h and "do_openvpn" in h.lower())
    assert a is not None

    m_tcp = re.search(r"[?&]tcp=(\d+)", a["href"])
    m_udp = re.search(r"[?&]udp=(\d+)", a["href"])

    if m_tcp and int(m_tcp.group(1)) > 0:
        assert p["openvpn"]["tcp"]["supported"] is True
        assert p["openvpn"]["tcp"]["port"] == int(m_tcp.group(1))
    else:
        assert p["openvpn"]["tcp"]["supported"] is False
        assert p["openvpn"]["tcp"]["port"] is None

    if m_udp and int(m_udp.group(1)) > 0:
        assert p["openvpn"]["udp"]["supported"] is True
        assert p["openvpn"]["udp"]["port"] == int(m_udp.group(1))

    assert p["openvpn"]["configAvailable"] is True

    # --- SSTP: port null unless printed (§9) ---
    sstp_cell = find_cell("SSTP Hostname")

    hm = re.search(
        r"SSTP\s+Hostname\s*:\s*([A-Za-z0-9._-]+)(?::(\d+))?",
        sstp_cell,
    )

    if hm:
        assert p["sstp"]["supported"] is True
        assert p["sstp"]["hostname"] == hm.group(1)
        if hm.group(2):
            assert p["sstp"]["port"] == int(hm.group(2))
        else:
            assert p["sstp"]["port"] is None

    # --- L2TP ---
    l2tp_supported_anywhere = any("L2TP" in c for c in cells)
    assert l2tp_supported_anywhere == p["l2tpIpsec"]["supported"]
    if l2tp_supported_anywhere:
        assert p["l2tpIpsec"]["port"] == 1701

    # --- Performance sanity ---
    perf = server["performance"]
    assert perf["speedMbps"] > 0
    assert perf["sessions"] >= 0
    assert perf["uptimeDays"] > 0     # 93 days in this snapshot

    # --- Provenance present (§14) ---
    fs = server["fieldSources"]
    assert fs["identity.ip"] == ["html"]
    assert fs["protocols.softether.tcp.port"] == ["html"]
    assert fs["protocols.openvpn.udp.port"] == ["html"]


def test_openvpn_udp_only_from_url_params(servers, fixture_html):
    """§31 Test 5 — REAL server whose do_openvpn link carries
    tcp=0&udp=1195-style params: TCP must stay unsupported."""
    target = None

    soup = BeautifulSoup(fixture_html, "html.parser")

    for a in soup.find_all("a", href=True):
        href_lower = a["href"].lower()

        if "do_openvpn" not in href_lower:
            continue

        query = dict(
            chunk.split("=", 1)
            for chunk in a["href"].split("?")[-1].split("&")
            if "=" in chunk
        )

        if query.get("tcp") == "0" and query.get("udp", "").isdigit():
            target = (a["href"], query)
            break

    if target is None:
        pytest.skip("no tcp=0&udp=N server in current snapshot")

    href, query = target

    fqdn = re.search(r"fqdn=([^&]+)", href).group(1)
    server = servers[fqdn]

    p = server["protocols"]

    assert p["openvpn"]["tcp"]["supported"] is False
    assert p["openvpn"]["tcp"]["port"] is None
    assert p["openvpn"]["udp"]["supported"] is True
    assert p["openvpn"]["udp"]["port"] == int(query["udp"])
    assert p["openvpn"]["configAvailable"] is True


def test_6_sstp_without_port_stays_null(servers, fixture_html):
    """§31 Test 6: any snapshot server whose SSTP cell prints no
    :port must yield port=null (never a guessed 443)."""
    checked = 0

    soup = BeautifulSoup(fixture_html, "html.parser")

    for tr in soup.find_all("tr"):
        text = tr.get_text(" ", strip=True)

        if "SSTP Hostname" not in text:
            continue

        m = re.search(
            r"SSTP\s+Hostname\s*:\s*([A-Za-z0-9._-]+)(?::(\d+))?",
            text,
        )

        assert m, f"SSTP cell unparseable: {text[:120]}"

        host = m.group(1).lower()

        server = servers.get(host)
        assert server is not None, f"{host} not parsed"

        sstp = server["protocols"]["sstp"]

        assert sstp["supported"] is True

        if m.group(2):
            assert sstp["port"] == int(m.group(2))
        else:
            assert sstp["port"] is None          # ← the invariant

        checked += 1

    assert checked > 0


def test_7_softether_udp_only_never_borrows_openvpn_tcp(
    servers,
    fixture_html,
):
    """§31 Test 7 — REAL row whose SSL-VPN cell says 'UDP: Supported'
    without TCP: udp=true/port=null and TCP must NOT be borrowed from
    the OpenVPN column of the same row (mission Bug 1 invariant)."""
    target_row = None

    soup = BeautifulSoup(fixture_html, "html.parser")

    for table in soup.find_all("table", id="vg_hosts_table_id"):
        for tr in table.find_all("tr"):
            tds = tr.find_all("td")

            if len(tds) < 8:
                continue

            first_class = tds[0].get("class") or []

            if first_class and "vg_table_header" in first_class[0]:
                continue

            se_text = tds[4].get_text(" ", strip=True)
            ovpn_text = tds[6].get_text(" ", strip=True)

            if (
                "SSL-VPN" in se_text
                and re.search(r"UDP\s*:\s*Supported", se_text)
                and not re.search(r"TCP\s*:", se_text)
                and re.search(r"TCP\s*:\s*\d+", ovpn_text)
            ):
                target_row = tds
                break

        if target_row:
            break

    if target_row is None:
        pytest.skip("no SE-UDP-only + OVPN-TCP row in current snapshot")

    tds = target_row

    host_blob = tds[1].get_text(" ", strip=True)
    hm = re.search(r"[A-Za-z0-9._-]+\.opengw\.net", host_blob)
    assert hm

    hostname = hm.group(0).lower()
    server = servers[hostname]

    se = server["protocols"]["softether"]

    assert se["supported"] is True
    assert se["udp"]["supported"] is True
    assert se["udp"]["port"] is None            # §6
    assert se["tcp"]["supported"] is False
    assert se["tcp"]["port"] is None

    # Explicit prohibition check: OpenVPN TCP exists in this row but
    # was NOT copied into SoftEther.
    ovpn_tcp_m = re.search(
        r"TCP\s*:\s*(\d+)",
        tds[6].get_text(" ", strip=True),
    )
    assert ovpn_tcp_m is not None
    assert se["tcp"]["port"] != int(ovpn_tcp_m.group(1))
    assert server["protocols"]["openvpn"]["tcp"]["port"] == (
        int(ovpn_tcp_m.group(1))
    )


def test_operator_by_prefix_stripped(servers):
    """The operator cell prints 'By <name>'; the 'By ' prefix must
    be stripped (was broken by a double-escaped regex)."""
    server = servers.get("public-vpn-206.opengw.net")
    assert server is not None

    name = server["operator"]["name"]

    assert name == "Daiyuu Nobori, Japan. Academic Use Only."
    assert not re.match(r"^by\s", name, re.I)


def test_nested_table_with_stray_closing_td_survives():
    """Live-page layout: the hosts table is nested in <td><p><span>
    and each header block carries an UNMATCHED </td> before </tr>.
    Under html.parser that stray tag unwinds the stack to the outer
    <td> and silently drops every data row — _make_soup must
    sanitize/parse it so the rows survive."""
    doc = (
        "<table id='outer'><tr><td id='cell'><p><span id='Label_Table'>"
        "<table border='1' id='vg_hosts_table_id'>"
        "<tr>"
        "<td class='vg_table_header'>Country</td>"
        "<td class='vg_table_header'>DDNS hostname</td>"
        "<td class='vg_table_header'>SSL-VPN</td>"
        "<td class='vg_table_header'>OpenVPN</td>"
        "\n</td>\n</tr>"
        "<tr>"
        "<td>Japan</td>"
        "<td>public-vpn-1.opengw.net 192.0.2.1</td>"
        "<td>SSL-VPN TCP: 443</td>"
        "<td>OpenVPN Config file</td>"
        "</tr>"
        "</table></span></p></td></tr></table>"
    )

    soup = vg._make_soup(doc)
    table = vg.select_hosts_table(vg.find_hosts_tables(soup))

    assert table is not None

    data_rows = [
        tr
        for tr in table.find_all("tr")
        if not any(
            "vg_table_header" in (td.get("class") or [])
            for td in tr.find_all("td")
        )
    ]

    assert len(data_rows) == 1, "data row lost to the stray </td>"

    servers = vg.parse_html(doc, "html")

    assert len(servers) == 1
    assert servers[0]["identity"]["ip"] == "192.0.2.1"
    assert servers[0]["protocols"]["softether"]["tcp"]["port"] == 443


def test_column_map_derived_not_hardcoded(fixture_html):
    soup = BeautifulSoup(fixture_html, "html.parser")
    table = vg.select_hosts_table(vg.find_hosts_tables(soup))

    assert table is not None, "real hosts table not selectable"

    colmap = vg.build_column_map(table)

    # Verified against the live DOM header order.
    assert colmap["country"] == 0
    assert colmap["host"] == 1
    assert colmap["sessions"] == 2
    assert colmap["perf"] == 3
    assert colmap["softether"] == 4
    assert colmap["l2tp"] == 5
    assert colmap["openvpn"] == 6
    assert colmap["sstp"] == 7
    assert colmap["operator"] == 8
    assert colmap["score"] == 9


def test_duplicate_tables_do_not_break_selection(fixture_html):
    """The live page embeds THREE tables with the same id; the
    selector must pick the real hosts list."""
    soup = BeautifulSoup(fixture_html, "html.parser")
    candidates = vg.find_hosts_tables(soup)

    # The fixture stores only the genuine hosts table; ensure the
    # selector still accepts it.
    assert vg.select_hosts_table(candidates) is candidates[0]


def test_uptime_hours_normalized():
    assert vg.parse_uptime_days("11 hours") == round(11 / 24, 4)
    assert vg.parse_uptime_days("93 days") == 93.0
    assert vg.parse_uptime_days("45 mins") == round(45 / 1440, 4)
    assert vg.parse_uptime_days("no uptime here") == 0.0
